export const emailPattern: RegExp;
export const passwordPattern: RegExp;

export function truncate(value: string, size: number, suffix: string): string | null;
export function cssRuleExists(className: string): boolean;
export function UUID(): string;
export function isNull(value: any): boolean;
export function isString(value: any): boolean;
export function isUndefined(value: any): boolean;
export function isDefined(value: any): boolean;
export function isObject(value: any): boolean;
export function isNumber(value: any): boolean;
export function isDate(value: any): boolean;
export function isArray(value: any): boolean;
export function isFunction(value: any): boolean;
export function isElement(node: any): boolean;
export function isRegExp(value: any): boolean;
export function noop(): void;
export function getAspectRatioFit(srcWidth: number, srcHeight: number, maxWidth: number, maxHeight: number): { ratio: number, width: number, height: number };
export function extend(dst: Object, ...sources: Object[]): Object;
export function merge(dst: Object, ...sources: Object[]): Object;
export function forEach(obj: any, iterator: Function, context?: Object): Object;
